# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itcast_subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nami_user',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='nami_user',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='nami_user',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='nami_user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='nami_user',
            name='username',
        ),
        migrations.AddField(
            model_name='nami_user',
            name='admin',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nami_user',
            name='ase_password',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nami_user',
            name='create_on',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nami_user',
            name='firstname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nami_user',
            name='lastname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nami_user',
            name='login',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nami_user',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
