# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itcast_subject', '0002_auto_20160817_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nami_user',
            name='create_on',
        ),
    ]
