# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itcast_subject', '0004_nami_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nami_user',
            old_name='Email',
            new_name='email',
        ),
    ]
