# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itcast_subject', '0006_auto_20160817_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nami_user',
            name='login',
        ),
    ]
